// flow-typed signature: 267e2edce835a76efd3b1fdf6698e50a
// flow-typed version: <<STUB>>/roslib-client_vgit+https://github.com/samiamlabs/roslibjs-client.git#master/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'roslib-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'roslib-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'roslib-client/build/roslibjs-client' {
  declare module.exports: any;
}

declare module 'roslib-client/src/browser' {
  declare module.exports: any;
}

declare module 'roslib-client/src/Connection' {
  declare module.exports: any;
}

declare module 'roslib-client/src/Constants' {
  declare module.exports: any;
}

declare module 'roslib-client/src/RosLibJsClient' {
  declare module.exports: any;
}

declare module 'roslib-client/src/ServiceManager' {
  declare module.exports: any;
}

declare module 'roslib-client/src/TopicManager' {
  declare module.exports: any;
}

declare module 'roslib-client/tests/test' {
  declare module.exports: any;
}

declare module 'roslib-client/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'roslib-client/build/roslibjs-client.js' {
  declare module.exports: $Exports<'roslib-client/build/roslibjs-client'>;
}
declare module 'roslib-client/src/browser.js' {
  declare module.exports: $Exports<'roslib-client/src/browser'>;
}
declare module 'roslib-client/src/Connection.js' {
  declare module.exports: $Exports<'roslib-client/src/Connection'>;
}
declare module 'roslib-client/src/Constants.js' {
  declare module.exports: $Exports<'roslib-client/src/Constants'>;
}
declare module 'roslib-client/src/RosLibJsClient.js' {
  declare module.exports: $Exports<'roslib-client/src/RosLibJsClient'>;
}
declare module 'roslib-client/src/ServiceManager.js' {
  declare module.exports: $Exports<'roslib-client/src/ServiceManager'>;
}
declare module 'roslib-client/src/TopicManager.js' {
  declare module.exports: $Exports<'roslib-client/src/TopicManager'>;
}
declare module 'roslib-client/tests/test.js' {
  declare module.exports: $Exports<'roslib-client/tests/test'>;
}
declare module 'roslib-client/webpack.config.js' {
  declare module.exports: $Exports<'roslib-client/webpack.config'>;
}
